spring:
  application:
    name: asset-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  cloud:
    openfeign:
      client:
        config:
          employee-app:
            url: http://localhost:8082/api/v1/employees

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
  
  mvc:
    apiversion:
      use:
        path-segment:  0
      required: true

server:
  servlet:
    context-path: /api


